/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev at Thu Oct  3 21:52:45 2024. */

#include "app/proto/payload.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(DINOLABS_PAYLOAD_PACAKGE, dinolabs_payload_pacakge_t, AUTO)


PB_BIND(DINOLABS_POWER_BOARD, dinolabs_power_board_t, AUTO)


PB_BIND(DINOLABS_EXPERIMENT_SENSOR, dinolabs_experiment_sensor_t, AUTO)


PB_BIND(DINOLABS_EXPERIMENT_BOARD, dinolabs_experiment_board_t, AUTO)


PB_BIND(DINOLABS_TEC, dinolabs_tec_t, AUTO)


PB_BIND(DINOLABS_FAN, dinolabs_fan_t, AUTO)


PB_BIND(DINOLABS_COOLING_SYSTEM, dinolabs_cooling_system_t, AUTO)


PB_BIND(DINOLABS_IMU, dinolabs_imu_t, AUTO)


PB_BIND(DINOLABS_SYSTEM_STATE, dinolabs_system_state_t, AUTO)





